### ISSUE TITLE
An error 

### ISSUE THREAD

**Issue by RevyaM** [TingTingin/TikTokDiffusion#11]
Happened after diffusion had converted a video into images, the original framerate was lowered from 60 to 30

Checking for frames to skip using a ratio of 81
Found 719 similar image(s) to skip
Generating 719 skipped frames
Exception in thread Thread-418 (this_func):
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\SD\TikTokDiffusion\TikTokDiffusion.py", line 1024, in this_func
    status = track.test_main(image_folder=image_folder, skip_if_exists=skip_if_exists, steps=steps,
  File "D:\SD\TikTokDiffusion\track.py", line 977, in test_main
    run(source=Path(image_folder), **vars(opt),
  File "D:\SD\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\SD\TikTokDiffusion\track.py", line 934, in run
    RIFE.frame_generator(path_of_images=save_folder, save_folder=generated_images_save_folder)
  File "D:\SD\TikTokDiffusion\rife\RIFE.py", line 148, in frame_generator
    missing_pairs, zfill_amount = get_missing_imgs(path_of_images)
  File "D:\SD\TikTokDiffusion\rife\RIFE.py", line 143, in get_missing_imgs
    zfill_amount = len(str(first_found_pattern))
UnboundLocalError: local variable 'first_found_pattern' referenced before assignment

**Comment by RevyaM** [comment]
Tried to use a 1 second clip with 25 framerate and no spaces in the name, ended up with the very same error.

**Comment by TingTingin** [comment]
are the frames the exact same?

**Comment by RevyaM** [comment]
Could you elaborate a bit? 
If you're asking if the frames extracted from the video are the same, then they're not. 
They're similar, but as you scroll down you would see how they're slowly changing, like in the video.

**Comment by TingTingin** [comment]
When you say "after diffusion" did tiktok diffusion generate these frames? 

If so is the image folder box pointing to the correct folder?

**Comment by RevyaM** [comment]
Ah, I meant that after TikTokDiffusion converted a source into frames (images). 
In console, it points to the correct folder: 
"image 37/37 D:\SD\outputs\Tiktok Diffusion\Images From Videos\test1mp4\37.png: 640x608  (no detections)
None"

**Comment by TingTingin** [comment]
Are there people in the image? if it doesnt detect a person it skips the frame

**Comment by RevyaM** [comment]
At first, I had used a drawn characters and it didn't get recognized at all. 
Then, I took a random short from youtube at it indeed recognized them. Although the result was pretty much the same, ignoring the promt. 
Trying another video right afterwards created a weird mix of both (steps were going minus 50, then -51). 
I'll try another video with a drawn character since it did seem to recognize them.

**Comment by TingTingin** [comment]
It can only detect real human people (from recorded video) it might work for some drawings if the look is similar to real people but it won't be as accurate. also what do you mean by "ignoring the prompt"

**Comment by RevyaM** [comment]
By ignoring the promt I meant that I simply tried to change a hair color to see if it works, however, it stayed original. 
Also, it can, apparently, detect drawn characters.

**Comment by TingTingin** [comment]
If your changing stuff like the color the denoising will have to be higher

**Comment by RevyaM** [comment]
Aha, I see, how much denoising you can suggest?

**Comment by TingTingin** [comment]
you have to keep increasing until it works

**Comment by RevyaM** [comment]
Alright, I see.
