### ISSUE TITLE
ImportError: cannot import name 'pairwise' from 'itertools' (unknown location)

### ISSUE THREAD

**Issue by Archangel39** [TingTingin/TikTokDiffusion#12]
Hello!)

Traceback (most recent call last):
  File "F:\AI\TikTokDiffusion\TikTokDiffusion.py", line 84, in <module>
    import track
  File "F:\AI\TikTokDiffusion\track.py", line 53, in <module>
    import RIFE
  File "F:\AI\TikTokDiffusion\rife\RIFE.py", line 10, in <module>
    from itertools import pairwise
ImportError: cannot import name 'pairwise' from 'itertools' (unknown location)

Before that there were other problems related to lap and cython_bbox, but I seem to have solved it by manual installation. How to fix it?

**Comment by TingTingin** [comment]
You can install itertools into the environment by doing this you shouldn't have to do this though so something else might be wrong

open cmd and type

- cd "path to stable diffusion folder"
- venv\scripts\activate
- pip install itertools

**Comment by Archangel39** [comment]
Many thx! You are the best! In fact, the problem was in Ana'conda , old version of python. My carelessness, I need to sleep more.)
