### ISSUE TITLE
Launch Issue

### ISSUE THREAD

**Issue by androideve** [TingTingin/TikTokDiffusion#18]
I'm using a previous commit of stable-diffusion-webui that goes back to when TikTokDiffusion was released (1e30e4d9ebd9c36ccee43ec0e61c6ab490171614). The webui launches without issue, but the TikTokDiffusion app gives the following error and will not show the GUI:

> Checking TikTokDiffusion...
> Checking TikTokDiffusion Requirement: gitpython
> Checking TikTokDiffusion Requirement: ipython
> Checking TikTokDiffusion Requirement: matplotlib
> Checking TikTokDiffusion Requirement: numpy
> Checking TikTokDiffusion Requirement: cv2
> Checking TikTokDiffusion Requirement: orjson
> Checking TikTokDiffusion Requirement: PIL
> Checking TikTokDiffusion Requirement: psutil
> Checking TikTokDiffusion Requirement: yaml
> Checking TikTokDiffusion Requirement: requests
> Checking TikTokDiffusion Requirement: scipy
> Checking TikTokDiffusion Requirement: thop
> Checking TikTokDiffusion Requirement: SSIM_PIL
> Checking TikTokDiffusion Requirement: moviepy
> Checking TikTokDiffusion Requirement: sklearn
> Checking TikTokDiffusion Requirement: dface
> Checking TikTokDiffusion Requirement: tqdm
> Checking TikTokDiffusion Requirement: flet
> Checking TikTokDiffusion Requirement: static_ffmpeg
> Checking TikTokDiffusion Requirement: ffmpeg
> Checking TikTokDiffusion Requirement: tensorboard
> Checking TikTokDiffusion Requirement: pandas
> Checking TikTokDiffusion Requirement: seaborn
> Checking TikTokDiffusion Requirement: easydict
> Checking TikTokDiffusion Requirement: gdown
> Checking TikTokDiffusion Requirement: lap
> Checking TikTokDiffusion Requirement: cython_bbox
> Checking TikTokDiffusion Requirement: filterpy
> Checking TikTokDiffusion Requirement: pyopencl
> Checking TikTokDiffusion Requirement: yt_dlp
> Launching Stable Diffusion With TikTokDiffusion
> Successfully connected to 127.0.0.1:7860
> Unhandled error processing page session : Traceback (most recent call last):
>   File "C:\ai\stable-diffusion-webui.tiktok\venv\lib\site-packages\flet\flet.py", line 302, in on_session_created
>     session_handler(page)
>   File "C:\ai\stable-diffusion-webui.tiktok\TikTokDiffusion\TikTokDiffusion.py", line 528, in main
>     sampler = option.get("name")
> AttributeError: 'str' object has no attribute 'get'

**Comment by TingTingin** [comment]
Can you try the newest version I think this is an issue if there's traffic on your network the UI launches but doesn't respond so when TikTokDiffusion tries to get the samplers it closes

**Comment by androideve** [comment]
Used a fresh install of the newest automatic1111 commit and that worked. TY!
