### ISSUE TITLE
stuck at waiting for stable diffusion popup

### ISSUE THREAD

**Issue by bwtdozer** [TingTingin/TikTokDiffusion#8]
installed and launched tiktok diffusion.  two cmd prompts open and run.  the tiktok diffusion program opens but stays on the waiting for stable diffusion server.  loading bar keeps going and going.  can't proceed past there

**Comment by TingTingin** [comment]
can you connect to sd at this address? http://127.0.0.1:7860/

**Comment by bwtdozer** [comment]
yes, stable diffusion connects at http://127.0.0.1:7860/ .  the cmd runs and launchs the tiktok diffusion ui and runs the stable diffusion cmd and that runs. I open can open SD but when I look at the tiktok diffusion it keeps saying waiting on sd server

**Comment by bwtdozer** [comment]
![Screenshot_20230225_070730](https://user-images.githubusercontent.com/124959824/221386868-cda1ee4c-e19a-4306-a9cf-c67ac0f9a3bc.png)

**Comment by bwtdozer** [comment]
rebooted my computer and tried tik tok diffuser and it now works.  Guess after installing needed a restart.

**Comment by TingTingin** [comment]
glad to hear its working
