### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by Grafarii** [TingTingin/TikTokDiffusion#9]
![image](https://user-images.githubusercontent.com/88216975/221386493-e722e7b0-4627-41a9-84c0-35db4c9a4f68.png)

**Comment by Grafarii** [comment]
![image](https://user-images.githubusercontent.com/88216975/221386774-10021f5b-6f21-404f-9bfc-35baeba9ef37.png)

**Comment by Grafarii** [comment]
![image](https://user-images.githubusercontent.com/88216975/221391545-f83a4d83-8cda-4a3c-8737-7a80f500eec0.png)
this line seems to be the issue, i don't know why.

**Comment by Grafarii** [comment]
![image](https://user-images.githubusercontent.com/88216975/221391564-b1e9da2c-b39f-4f2e-8c8e-ae4d8d32dd47.png)
this line seems to be the issue, i don't know why.

**Comment by TingTingin** [comment]
is it working do the samplers show up properly?

**Comment by Grafarii** [comment]
no, it doesn't open at all if that line is in the script

**Comment by Grafarii** [comment]
if you completely delete that part of the code that i showed in the screenshot, it will open but the samplers won't show up

**Comment by Grafarii** [comment]
i reinstalled everything, even python and upgraded pip, now it works

**Comment by VaIerus** [comment]
I'm having this same issue - I did the same as @Grafarii but not getting anywhere. Even updated pip via venv and still nothing. the exact error is: 
`  
Successfully connected to 127.0.0.1:7860
Unhandled error processing page session : Traceback (most recent call last):
File "F:\Library\stable-diffusion-webui-master\venv\lib\site-packages\flet\flet.py", line 302, in on_session_created
    session_handler(page)
  File "F:\Library\stable-diffusion-webui-master\TikTokDiffusion\TikTokDiffusion.py", line 1010, in main
    sampler = option.get("name")
AttributeError: 'str' object has no attribute 'get'_`


Running on Python 3.10.9

**Comment by VaIerus** [comment]
> I'm having this same issue - I did the same as @Grafarii but not getting anywhere. Even updated pip via venv and still nothing. the exact error is: ` Successfully connected to 127.0.0.1:7860 Unhandled error processing page session : Traceback (most recent call last): File "F:\Library\stable-diffusion-webui-master\venv\lib\site-packages\flet\flet.py", line 302, in on_session_created session_handler(page) File "F:\Library\stable-diffusion-webui-master\TikTokDiffusion\TikTokDiffusion.py", line 1010, in main sampler = option.get("name") AttributeError: 'str' object has no attribute 'get'_`
> 
> Running on Python 3.10.9

Fixed this issue by adding 
`set COMMANDLINE_ARGS=--api`
to the tiktok-diffusion-webui-user.bat file
